services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amazingwebstore
    ports:
      - "3306:3306"
    networks:
      - webstore-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  webstore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webstore
    restart: unless-stopped
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/amazingwebstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./src/main/resources/static/images:/app/src/main/resources/static/images
    networks:
      - webstore-network

networks:
  webstore-network:
    driver: bridge